name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-rootless:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@main

      - name: Checkout theos/theos
        uses: actions/checkout@main
        with:
          repository: theos/theos
          ref: master
          submodules: recursive
          path: theos

      - name: Checkout SDKs
        uses: actions/checkout@main
        with:
          repository: theos/sdks
          ref: master
          sparse-checkout: |
            iPhoneOS15.6.sdk
            iPhoneOS16.5.sdk
          path: theos/sdks

      - name: Install dependencies
        run: HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1 HOMEBREW_NO_AUTO_UPDATE=1 brew install make xz ldid

      - name: Set THEOS environment variable
        run: echo "THEOS=$GITHUB_WORKSPACE/theos" >> $GITHUB_ENV

      - name: Checkout AltList
        uses: actions/checkout@main
        with:
          repository: opa334/AltList
          ref: main
          path: altlist

      - name: Install AltList
        working-directory: altlist
        run: make clean && make FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless && mkdir -p "$THEOS/lib/iphone/rootless/lib" && cp -Rv "./.theos/obj/AltList.framework" "$THEOS/lib/iphone/rootless"

      - name: Build package (rootless)
        run: THEOS=theos gmake clean package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

      - name: Upload a Build Artifact (rootless)
        uses: actions/upload-artifact@v3
        with:
          name: packages iphoneos-arm64 (rootless)
          path: packages/*_iphoneos-arm64.deb
